### PR TITLE
Added a new word to the dictionary (README.md)

### PR DESCRIPTION
**Pull request by dchidindu5**
Added a new word **Encapsulation** to the dictionary

### CODE REVIEW

**Comment by dchidindu5** [comment]
Please @FSipiano Review and merge. Thanks

**Comment by FSipiano** [comment]
Very thorough definition, it's great. As OOP has already been defined, you can link your definition to it to give people reading it some context

Thanks!

**Comment by dchidindu5** [comment]
@FSipiano from my observation OOP is not defined in the dictionary

**Comment by FSipiano** [comment]
Object is defined, and many people tried to define OOP already. I'm surprised that it's not in there yet. Feel free to write your own definition

**Pull request merged**
