### PR TITLE
Add Server Side Rendering

### PR DESCRIPTION
**Pull request by stevenanthonyrevo**
Contributed "SSR" to newbie dictionary list

### CODE REVIEW

**Review by stevenanthonyrevo — COMMENTED** [review]
Contributed "TTFB" to newbie dictionary list

**Comment by FSipiano** [comment]
Great contributions, thanks! Can you make sure they are super newbie friendly ('load up' as opposed to 'rendering') etc, and also you have a small typo for 'measurements' 👍

**Comment by stevenanthonyrevo** [comment]
Sounds good, I have revised and added more info to each term!

**Comment by FSipiano** [comment]
Thanks!

**Pull request merged**
