### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shradha1612**
Firebase

### CODE REVIEW

**Comment by FSipiano** [comment]
Thanks for your contribution! Please can you add in a definition of 'authentication' - I don't think we have a definition of that already, and it would certainly help people to understand!
Thanks!

**Comment by shradha1612** [comment]
Sure

**Comment by shradha1612** [comment]
Authentication

**Comment by shradha1612** [comment]
Authentication

**Comment by shradha1612** [comment]
Authentication

**Pull request closed without merging**
